### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by luismanson** [Paravantage/graylog-xg-guide#1]
Hello, I cant get this to work, and fields _look_ right. Are you still using it?
Thanks for sharing

**Comment by GaryParr** [comment]
Oh wow, sorry for not responding months ago!  Unfortunately no, our experiment with Graylog and XG ended a while back. To the best of my knowledge, this was working "as-is" through a few version updates of both products, but I can't speak to the latest releases. Best of luck!
